
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUALS LPAREN MINUS NUMBER PLUS RPAREN TIMES VARIABLEstatement : VARIABLE EQUALS expression\n    expression : expression PLUS term\n               | expression MINUS term\n               | term\n    \n    term : term TIMES factor\n         | term DIVIDE factor\n         | factor\n    factor : NUMBERfactor : VARIABLEfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'VARIABLE':([0,3,9,10,11,12,13,],[2,4,4,4,4,4,4,]),'$end':([1,4,5,6,7,8,15,16,17,18,19,],[0,-9,-1,-4,-7,-8,-2,-3,-5,-6,-10,]),'EQUALS':([2,],[3,]),'NUMBER':([3,9,10,11,12,13,],[8,8,8,8,8,8,]),'LPAREN':([3,9,10,11,12,13,],[9,9,9,9,9,9,]),'TIMES':([4,6,7,8,15,16,17,18,19,],[-9,12,-7,-8,12,12,-5,-6,-10,]),'DIVIDE':([4,6,7,8,15,16,17,18,19,],[-9,13,-7,-8,13,13,-5,-6,-10,]),'PLUS':([4,5,6,7,8,14,15,16,17,18,19,],[-9,10,-4,-7,-8,10,-2,-3,-5,-6,-10,]),'MINUS':([4,5,6,7,8,14,15,16,17,18,19,],[-9,11,-4,-7,-8,11,-2,-3,-5,-6,-10,]),'RPAREN':([4,6,7,8,14,15,16,17,18,19,],[-9,-4,-7,-8,19,-2,-3,-5,-6,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([3,9,],[5,14,]),'term':([3,9,10,11,],[6,6,15,16,]),'factor':([3,9,10,11,12,13,],[7,7,7,7,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> VARIABLE EQUALS expression','statement',3,'p_statement_assign','analisis-sintak.py',63),
  ('expression -> expression PLUS term','expression',3,'p_expression_binop','analisis-sintak.py',69),
  ('expression -> expression MINUS term','expression',3,'p_expression_binop','analisis-sintak.py',70),
  ('expression -> term','expression',1,'p_expression_binop','analisis-sintak.py',71),
  ('term -> term TIMES factor','term',3,'p_term_binop','analisis-sintak.py',78),
  ('term -> term DIVIDE factor','term',3,'p_term_binop','analisis-sintak.py',79),
  ('term -> factor','term',1,'p_term_binop','analisis-sintak.py',80),
  ('factor -> NUMBER','factor',1,'p_factor_number','analisis-sintak.py',86),
  ('factor -> VARIABLE','factor',1,'p_factor_variable','analisis-sintak.py',91),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_parentheses','analisis-sintak.py',96),
]
